services:
  app:
    build: .
    container_name: contacts_app
    restart: always
    volumes:
      - ./app:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db_contacts_app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contacts_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
